# Generated by Django 5.2.4 on 2025-12-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('shop_id', models.CharField(max_length=50)),
                ('user_message', models.TextField()),
                ('assistant_response', models.TextField()),
                ('message_type', models.CharField(default='normal', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='shop_api_co_session_ad4a47_idx'), models.Index(fields=['shop_id'], name='shop_api_co_shop_id_e0c221_idx'), models.Index(fields=['timestamp'], name='shop_api_co_timesta_3de138_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionMetadata',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shop_id', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_preferences', models.JSONField(default=dict)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('session_status', models.CharField(default='active', max_length=20)),
                ('reservation_state', models.CharField(blank=True, max_length=50, null=True)),
                ('reservation_data', models.JSONField(default=dict)),
                ('pending_reservation', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['shop_id'], name='shop_api_se_shop_id_375722_idx'), models.Index(fields=['created_at'], name='shop_api_se_created_a51b71_idx'), models.Index(fields=['user_email'], name='shop_api_se_user_em_45c8bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_api.sessionmetadata')),
            ],
        ),
    ]
