# Generated by Django 5.2.12 on 2026-03-12 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('number_of_people', models.IntegerField(default=1)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('services', models.ManyToManyField(blank=True, to='business.service')),
            ],
            options={
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_reservations_per_day', models.IntegerField(blank=True, default=10, null=True)),
                ('cancellation_deadline_hours', models.IntegerField(default=24)),
                ('operating_hours_start', models.TimeField(blank=True, null=True)),
                ('operating_hours_end', models.TimeField(blank=True, null=True)),
                ('buffer_time_minutes', models.IntegerField(default=0, help_text='Minutes between reservations')),
                ('advance_notice_hours', models.IntegerField(default=0, help_text='Minimum hours before booking')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
    ]
